import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const oswald = localFont({
  src: "../assets/fonts/oswald.ttf",
  variable: "--font-oswald",
});
const manrope = localFont({
  src: "../assets/fonts/manrope.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${manrope.className}`}>
        {children}
      </body>
    </html>
  );
}
