import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Footer from "./footer";
import Nav from "./nav";

const oswald = localFont({
  src: "../assets/fonts/oswald.ttf",
  variable: "--font-oswald",
});
const manrope = localFont({
  src: "../assets/fonts/manrope.ttf",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Techno International Group",
    default: "Homepage | Techno International Group",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${manrope.className}`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
